name: Building

on:
  push:
    branches:
    - macos
  workflow_dispatch:
  workflow_call:

jobs:
  build-on-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache
      uses: actions/cache@v4.2.0
      env:
        cache-name: cache-flutter
      with:
        path: |
          ./flutter_scom/build/
          ./flutter_scom/.dart_tool/
          ~/.pub-cache/
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./flutter_scom/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-

    - name: Configure
      run: rm ./flutter_scom/macos/Runner.xcodeproj/project.pbxproj && cp ./flutter_scom/macos/Runner.xcodeproj/project_arm64.pbxproj ./flutter_scom/macos/Runner.xcodeproj/project.pbxproj
    - name: flutter-install
      run: curl -O https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_arm64_3.27.1-stable.zip && unzip ./flutter_macos_arm64_3.27.1-stable.zip -d . # TODO: how to make it quiet
    - name: build
      run: cd flutter_scom && ../flutter/bin/flutter config --no-analytics && ../flutter/bin/flutter config --no-cli-animations && ../flutter/bin/flutter pub get && ../flutter/bin/flutter build macos --verbose
    - name: bundle
      run: tar -zcvf ./macos-release.tar.gz ./flutter_scom/build/macos/Build/Products/Release/flutter_scom.app

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: macos-release
        path: macos-release.tar.gz