name: Building

on:
  push:
    branches:
    - flutter
    - flutter-develop
  workflow_dispatch:
  workflow_call:

jobs:
  build-on-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache
      uses: actions/cache@v4.2.0
      env:
        cache-name: cache-flutter
      with:
        path: |
          ./flutter_scom/build/
          ./flutter_scom/.dart_tool/
          ~/.pub-cache/
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./flutter_scom/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-

    # - name: pre-build
      # run: sudo apt-get update -y && sudo apt-get upgrade -y && sudo apt-get install -y curl git unzip xz-utils zip libglu1-mesa && sudo apt-get install -y clang cmake git ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev;
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: curl git unzip xz-utils zip libglu1-mesa clang cmake git ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev
        version: 1.0
    - name: flutter-install
      run: curl -O https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.27.0-stable.tar.xz && tar -xf ./flutter_linux_3.27.0-stable.tar.xz -C .
    - name: build
      run: cd flutter_scom && ../flutter/bin/flutter config --no-analytics && ../flutter/bin/flutter config --no-cli-animations && ../flutter/bin/flutter pub get && ../flutter/bin/flutter build linux
    - name: bundle
      run: tar -zcvf ./linux-release.tar.gz ./flutter_scom/build/linux/x64/release/bundle/

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: linux-release
        path: linux-release.tar.gz

  build-on-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache
      uses: actions/cache@v4.2.0
      env:
        cache-name: cache-flutter
      with:
        path: |
          ./flutter_scom/build/
          ./flutter_scom/.dart_tool/
          ~/.pub-cache/
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./flutter_scom/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-

    - name: flutter-install
      run: curl -O https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_3.27.0-stable.zip && Expand-Archive –Path .\flutter_windows_3.27.0-stable.zip -Destination .
    - name: build-flutter-scom
      run: cd flutter_scom && ../flutter/bin/flutter config --no-analytics && ../flutter/bin/flutter config --no-cli-animations && ../flutter/bin/flutter pub get && ../flutter/bin/flutter build windows
    - name: bundle
      run: Compress-Archive -Path ./flutter_scom/build/windows/x64/runner/Release/ -DestinationPath ./windows-release.zip

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: windows-release
        path: windows-release.zip

  build-on-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache
      uses: actions/cache@v4.2.0
      env:
        cache-name: cache-flutter
      with:
        path: |
          ./flutter_scom/build/
          ./flutter_scom/.dart_tool/
          ~/.pub-cache/
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./flutter_scom/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-

    - name: Configure
      run: rm ./flutter_scom/macos/Runner.xcodeproj/project.pbxproj && cp ./flutter_scom/macos/Runner.xcodeproj/project_arm64.pbxproj ./flutter_scom/macos/Runner.xcodeproj/project.pbxproj
    - name: flutter-install
      run: curl -O https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_arm64_3.27.1-stable.zip && unzip ./flutter_macos_arm64_3.27.1-stable.zip -d . # TODO: how to make it quiet
    - name: build
      run: cd flutter_scom && ../flutter/bin/flutter config --no-analytics && ../flutter/bin/flutter config --no-cli-animations && ../flutter/bin/flutter pub get && ../flutter/bin/flutter build macos --verbose
    - name: bundle
      run: tar -zcvf ./macos-release.tar.gz ./flutter_scom/build/macos/Build/Products/Release/flutter_scom.app

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: macos-release
        path: macos-release.tar.gz