name: Building

on:
  workflow_dispatch:

jobs:
  build-on-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: pre-build
      run: sudo apt-get update -y && sudo apt-get upgrade -y && sudo apt-get install -y curl git unzip xz-utils zip libglu1-mesa && sudo apt-get install -y clang cmake git ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev;
    - name: flutter-download
      run: curl -O https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.27.0-stable.tar.xz
    - name: flutter-install
      run: tar -xf ./flutter_linux_3.27.0-stable.tar.xz -C .
    - name: cmake-download
      run: curl -OJL https://github.com/Kitware/CMake/releases/download/v3.31.2/cmake-3.31.2-linux-x86_64.tar.gz
    - name: cmake-install
      run: tar -xf ./cmake-3.31.2-linux-x86_64.tar.gz -C .
    - name: build-flutter-scom
      run: cd flutter_scom && ../flutter/bin/flutter pub get && ../flutter/bin/flutter build linux
    - name: build-database
      run: cd database && mkdir cmake-build-debug && ../cmake-3.31.2-linux-x86_64/bin/cmake -S . -B ./cmake-build-debug && ../cmake-3.31.2-linux-x86_64/bin/cmake --build ./cmake-build-debug --target SCOM_database
    - name: bundle
      run: cp ./database/cmake-build-debug/libSCOM_database.so ./flutter_scom/build/linux/x64/release/bundle/lib/database.so && tar -zcvf ./linux-release.tar.gz ./flutter_scom/build/linux/x64/release/bundle/

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: linux-release
        path: linux-release.tar.gz

  build-on-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: flutter-download
      run: curl -O https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_3.27.0-stable.zip
    - name: flutter-install
      run: Expand-Archive –Path .\flutter_windows_3.27.0-stable.zip -Destination .
    - name: cmake-download
      run: curl -OJL https://github.com/Kitware/CMake/releases/download/v3.31.2/cmake-3.31.2-windows-x86_64.zip
    - name: cmake-install
      run: Expand-Archive –Path .\cmake-3.31.2-windows-x86_64.zip -Destination .
    - name: build-flutter-scom
      run: cd flutter_scom && ../flutter/bin/flutter pub get && ../flutter/bin/flutter build windows
    - name: build-database
      run: cd database && mkdir cmake-build-debug && ../cmake-3.31.2-windows-x86_64/bin/cmake -S . -B ./cmake-build-debug && ../cmake-3.31.2-windows-x86_64/bin/cmake --build ./cmake-build-debug --target SCOM_database
    - name: bundle
      run: copy ./database/cmake-build-debug/libSCOM_database.dll ./flutter/build/windows/x64/runner/Release/ && rename ./flutter/build/windows/x64/runner/Release/libSCOM_database.dll database.dll && tar -zcvf ../windows-release.tar.gz ../flutter_scom/build/windows/x64/runner/Release/

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: winodws-release
        path: windows-release.tar.gz
