name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: build

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      attestations: write

    steps:
    - name: download-windows-build
      uses: actions/download-artifact@v4.1.8
      with:
        # Name of the artifact to download. If unspecified, all artifacts for the run are downloaded.
        name: windows-release
        # Destination path. Supports basic tilde expansion. Defaults to $GITHUB_WORKSPACE
        path: .

    - name: download-linux-build
      uses: actions/download-artifact@v4.1.8
      with:
        # Name of the artifact to download. If unspecified, all artifacts for the run are downloaded.
        name: linux-release
        # Destination path. Supports basic tilde expansion. Defaults to $GITHUB_WORKSPACE
        path: .

    - name: Attest
      uses: actions/attest-build-provenance@v2
      with:
        subject-path: '*-release.*'

